version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=ibrahim
      - MONGO_PASSWORD=secret
      - SESSION_SECRET=secret
      
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ibrahim
      - MONGO_INITDB_ROOT_PASSWORD=mypassword