version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: itmrnetworks/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ibrahim
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis:alpine

volumes:
  mongo-db: